### PR TITLE
add isRegistered function

### PR DESCRIPTION
**Pull request by daniserrano7**
Add isRegistered() function to SDRegistry to check whether a token is registered or not.

### CODE REVIEW

**Review by hollygrimm — CHANGES_REQUESTED** [review]
@daniserrano7 Can you add an `unregisterGeoNFT()` call to the "geoNFT is registered" test?

**Review by dkent600 — COMMENTED** [review]
Is a little bit of solidity I've not used before but I imagine is fine.  It definitely appears to do what we're hoping for :-)

**Comment by daniserrano7** [comment]
> @daniserrano7 Can you add an `unregisterGeoNFT()` call to the "geoNFT is registered" test?

Done!

**Review by hollygrimm — APPROVED** [review]

**Comment by hollygrimm** [comment]
closes #36

**Pull request merged**
